import { RoutineData } from './types';

export const DEFAULT_ROUTINE_DATA: RoutineData = {
  id: 'spy-a-session-routine',
  title: 'SPY A‑SESSION DAY TRADER ROUTINE',
  subtitle: 'WAKE‑UP TO FLAT (6:30 AM – 11:15 AM EST)',
  timezone: 'America/New_York',
  updated_at: new Date().toISOString(),
  phases: [
    {
      id: 'phase-1',
      phaseNumber: 1,
      title: 'PHASE 1: PREP',
      timeWindow: '6:30 AM – 8:00 AM',
      startMinutes: 390, // 6:30 AM
      endMinutes: 480,   // 8:00 AM
      items: [
        { time: '6:30 AM', action: 'Wake up. No snooze.' },
        { time: '6:30 – 6:45 AM', action: 'Bathroom, splash face, water.' },
        { time: '6:45 – 7:45 AM', action: 'Gym or movement.' },
        { time: '7:45 – 8:00 AM', action: 'Shower, eat, sit at desk.' },
        { time: '8:00 AM', action: 'At desk. No phone. No social media. Focus begins.' },
      ],
    },
    {
      id: 'phase-2',
      phaseNumber: 2,
      title: 'PHASE 2: MACRO SCRUB',
      timeWindow: '8:00 AM – 8:30 AM',
      startMinutes: 480,
      endMinutes: 510,
      items: [
        { time: '8:00 AM', tool: 'ForexFactory.com', action: 'Find red folder events. If 10:00 AM event → write FLAT BY 9:55 on sticky note.' },
        { time: '8:05 AM', tool: 'TradingView', action: 'Check DXY, US10Y, USOIL daily direction.' },
        { time: '8:10 AM', tool: 'FinancialJuice.com', action: 'Scan headlines for geopolitical risk.' },
        { time: '8:15 AM', tool: 'Brain', action: 'Form macro bias: Bullish (Dollar/Yields/Oil down), Bearish (up), Mixed.' },
      ],
    },
    {
      id: 'phase-3',
      phaseNumber: 3,
      title: 'PHASE 3: DRAW THE MAP',
      timeWindow: '8:30 AM – 9:15 AM',
      startMinutes: 510,
      endMinutes: 555,
      items: [
        { time: '8:30 AM', action: 'Check ES1! / NQ1! futures.' },
        { time: '8:35 AM', action: 'On SPY 15‑min chart (Extended Hours ON), draw 4 lines: PDH, PDL, PMH, PML.' },
        { time: '8:45 AM', action: 'Switch to 5‑min chart. Add VWAP. Add Volume. Remove all other indicators (no EMA, no RSI).' },
        { time: '8:50 AM', action: 'Classify regime using the Opening Regimes table below.' },
        { time: '9:00 AM', action: 'Final check. Know your bias, your blackout times. Map is set.' },
      ],
    },
    {
      id: 'phase-4',
      phaseNumber: 4,
      title: 'PHASE 4: THE OPEN — HANDS OFF',
      timeWindow: '9:30 AM – 9:45 AM',
      startMinutes: 570,
      endMinutes: 585,
      description: 'Do not place a single order. Watch the 5‑min candles form. Let amateurs fight.',
      items: [
        { time: '9:45 AM', action: 'Confirm Bias: Price > VWAP → Longs only' },
        { time: '9:45 AM', action: 'Confirm Bias: Price < VWAP → Shorts only' },
        { time: '9:45 AM', action: 'Confirm Bias: Price stuck at VWAP → Wait' },
      ],
    },
    {
      id: 'phase-5',
      phaseNumber: 5,
      title: 'PHASE 5: EXECUTION WINDOW',
      timeWindow: '9:45 AM – 11:00 AM',
      startMinutes: 585,
      endMinutes: 660,
      description: 'You trade exactly one setup: the VWAP pullback.',
      items: [
        { time: 'Step 1', action: 'Wait for extension – Price must move $1.50–$2.00 away from VWAP first. No extension = no trade.' },
        { time: 'Step 2', action: 'Wait for pullback – Price retraces and touches VWAP. No touch = no trade.' },
        { time: 'Step 3', action: 'Wait for candle close – A 5‑min candle closes green (long) or red (short) at VWAP. Do not enter mid‑candle.' },
        { time: 'Step 4', action: 'Enter – 1 contract only. 1‑DTE or 2‑DTE option. Stop‑loss placed at structural swing low (long) or swing high (short) ± buffer.' },
        { time: 'Step 5', action: 'Targets – TP1: nearest structural level (PDH/PDL). TP2: next level (PMH/PML). Scale out 50% at TP1, move stop to breakeven, let runner ride.' },
        { time: 'Step 6', action: 'If price is stuck between PMH and PML → Do nothing. No trade is a valid trade.' },
      ],
    },
    {
      id: 'phase-6',
      phaseNumber: 6,
      title: 'PHASE 6: BLACKOUT & DATA RULES',
      timeWindow: '9:55 AM – 10:15 AM',
      startMinutes: 595,
      endMinutes: 615,
      items: [
        { time: '9:55 AM', action: 'If any Tier‑2 or Tier‑1 event at 10:00 AM → FLAT. Cancel all orders.' },
        { time: '10:00 AM', action: 'Do not jump into the first violent candle after data.' },
        { time: 'During Window', action: 'If a Fed speaker is scheduled, be flat 2 minutes before they start.' },
      ],
    },
    {
      id: 'phase-7',
      phaseNumber: 7,
      title: 'PHASE 7: FLATTEN THE BOOK',
      timeWindow: '11:00 AM – 11:15 AM',
      startMinutes: 660,
      endMinutes: 675,
      items: [
        { time: '11:00 AM', action: 'Assess position. Volume drying up.' },
        { time: '11:05 AM', action: 'If in profit, close or scale out completely.' },
        { time: '11:10 AM', action: 'MANDATORY FLAT. Close all positions. Cancel all orders. Zero exposure.' },
        { time: '11:15 AM', action: 'Close broker. Close charts. Do not check phone. Trading day is over.' },
      ],
    },
    {
      id: 'phase-8',
      phaseNumber: 8,
      title: 'PHASE 8: EVENING AUTOPSY',
      timeWindow: '8:00 PM – 8:30 PM',
      startMinutes: 1200, // 8:00 PM = 20*60
      endMinutes: 1230,   // 8:30 PM = 20.5*60
      items: [
        { time: '8:00 PM', action: 'Screenshot 5‑min chart (9:30‑11:30). Journal: regime, plan followed?, setup valid?, emotion felt, lesson learned.' },
        { time: '8:15 PM', action: 'Grade execution, not P&L.' },
        { time: '8:30 PM', action: 'Close journal. Tomorrow is fresh.' },
      ],
    },
  ],
  regimes: [
    {
      id: 'regime-1',
      regime: 'Inside Range',
      condition: 'PMH & PML both between PDL & PDH',
      action: 'Wait for breakout. No trades in chop.',
    },
    {
      id: 'regime-2',
      regime: 'Full Gap Up',
      condition: 'PML > PDH',
      action: 'Longs only. Watch backtest to PDH.',
    },
    {
      id: 'regime-3',
      regime: 'Full Gap Down',
      condition: 'PMH < PDL',
      action: 'Shorts only. Watch backtest to PDL.',
    },
    {
      id: 'regime-4',
      regime: 'Top Overhang',
      condition: 'PMH > PDH, PML ≥ PDL',
      action: 'Long bias. Short squeeze likely.',
    },
    {
      id: 'regime-5',
      regime: 'Bottom Overhang',
      condition: 'PML < PDL, PMH ≤ PDH',
      action: 'Long bias if reclaims VWAP. Reversal rally risk.',
    },
    {
      id: 'regime-6',
      regime: 'Wide Span',
      condition: 'PML < PDL and PMH > PDH',
      action: 'High vol. Both directions possible. VWAP decides bias.',
    },
  ],
  rules: [
    { id: 1, title: 'Cash is a Position', text: 'Cash is a position. Doing nothing is a trade.' },
    { id: 2, title: 'No Touch, No Trade', text: 'No touch, no trade. No VWAP tag = no entry.' },
    { id: 3, title: 'Wait for the Close', text: 'Wait for the close. Never enter a forming candle.' },
    { id: 4, title: 'Flat Means Flat', text: 'Flat means flat. At blackout times, zero exposure.' },
    { id: 5, title: 'One Loss Per Day', text: 'One loss per day. If your stop is hit, shut down the platform immediately. No second trade.' },
    { id: 6, title: 'The Plan is the Boss', text: 'The plan is the boss. Not your gut, not your P&L, not your ego.' },
    { id: 7, title: 'Journal Every Day', text: 'Journal every day. You learn from disciplined reviews, not wins.' },
  ],
  resetCommitment: 'This is your reset. Follow it letter by letter for 90 paper‑trading days. The 10 EMA is gone from your chart. You trade four lines, VWAP, and volume. Nothing else. You already know the setups work; you proved you can\'t execute them emotionally. Now prove you can. The market will be there tomorrow. Be better than you were today.',
};
